from PyQt5.QtCore import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setWindowTitle("Яндекс карты")
        MainWindow.resize(800, 470)
        MainWindow.setMinimumSize(QSize(800, 470))
        MainWindow.setMaximumSize(QSize(800, 470))
        self.centralwidget = QWidget(MainWindow)
        self.lbl_map = QLabel("", self.centralwidget)
        self.lbl_map.setGeometry(QRect(191, 10, 600, 450))
        self.lbl_map.setMinimumSize(QSize(600, 450))
        self.lbl_map.setMaximumSize(QSize(600, 450))
        self.widget = QWidget(self.centralwidget)
        self.widget.setGeometry(QRect(9, 9, 112, 100))
        self.verticalLayout = QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.lbl1 = QLabel("Введите координаты", self.widget)
        self.verticalLayout.addWidget(self.lbl1)
        self.horizontalLayout = QHBoxLayout()
        self.lbl2 = QLabel("Долгота", self.widget)
        self.horizontalLayout.addWidget(self.lbl2)
        self.dsp_width = QDoubleSpinBox(self.widget)
        self.dsp_width.setFocusPolicy(Qt.ClickFocus)
        self.dsp_width.setMinimum(-180)
        self.dsp_width.setMaximum(180)
        self.dsp_width.setValue(55.75)
        self.horizontalLayout.addWidget(self.dsp_width)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.lbl3 = QLabel("Широта", self.widget)
        self.horizontalLayout_2.addWidget(self.lbl3)
        self.dsp_long = QDoubleSpinBox(self.widget)
        self.dsp_long.setFocusPolicy(Qt.ClickFocus)
        self.dsp_long.setMinimum(-180)
        self.dsp_long.setMaximum(180)
        self.dsp_long.setValue(37.61)
        self.horizontalLayout_2.addWidget(self.dsp_long)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.btn_show = QPushButton("Отобразить карту", self.widget)
        self.verticalLayout.addWidget(self.btn_show)
        MainWindow.setCentralWidget(self.centralwidget)
