from PyQt5.QtCore import *
from PyQt5.QtWidgets import *


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.resize(800, 470)
        MainWindow.setMinimumSize(QSize(800, 470))
        MainWindow.setMaximumSize(QSize(800, 470))
        self.centralwidget = QWidget(MainWindow)
        self.lbl_map = QLabel("", self.centralwidget)
        self.lbl_map.setGeometry(QRect(191, 10, 600, 450))
        self.lbl_map.setMinimumSize(QSize(600, 450))
        self.lbl_map.setMaximumSize(QSize(600, 450))
        self.layoutWidget = QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QRect(9, 9, 112, 188))
        self.verticalLayout = QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.lbl1 = QLabel("Введите координаты", self.layoutWidget)
        self.verticalLayout.addWidget(self.lbl1)
        self.horizontalLayout = QHBoxLayout()
        self.lbl2 = QLabel("Широта", self.layoutWidget)
        self.horizontalLayout.addWidget(self.lbl2)
        self.dsp_width = QDoubleSpinBox(self.layoutWidget)
        self.dsp_width.setFocusPolicy(Qt.ClickFocus)
        self.dsp_width.setMinimum(-90.000000000000000)
        self.dsp_width.setMaximum(90.000000000000000)
        self.dsp_width.setValue(55.750000000000000)
        self.horizontalLayout.addWidget(self.dsp_width)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QHBoxLayout()
        self.lbl3 = QLabel("Долгота", self.layoutWidget)
        self.lbl3.setMaximumSize(QSize(50, 120))
        self.horizontalLayout_2.addWidget(self.lbl3)
        self.dsp_long = QDoubleSpinBox(self.layoutWidget)
        self.dsp_long.setFocusPolicy(Qt.ClickFocus)
        self.dsp_long.setMinimum(-180.000000000000000)
        self.dsp_long.setMaximum(180.000000000000000)
        self.dsp_long.setValue(37.609999999999999)
        self.horizontalLayout_2.addWidget(self.dsp_long)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.label = QLabel("Выберете слой", self.layoutWidget)
        self.verticalLayout.addWidget(self.label)
        self.rbtn_map = QRadioButton("Схема", self.layoutWidget)
        self.rbtn_map.setChecked(True)
        self.verticalLayout.addWidget(self.rbtn_map)
        self.rbtn_sat = QRadioButton("Спутник", self.layoutWidget)
        self.verticalLayout.addWidget(self.rbtn_sat)
        self.rbtn_skl = QRadioButton("Гибрид", self.layoutWidget)
        self.verticalLayout.addWidget(self.rbtn_skl)
        self.btn_show = QPushButton("Отобразить карту", self.layoutWidget)
        self.verticalLayout.addWidget(self.btn_show)
        MainWindow.setCentralWidget(self.centralwidget)
